version = 0.1

[dev.deploy.parameters]
stack_name = "s3-sns-dev"
s3_bucket = "s3-sns-sam-artifacts"
s3_prefix = "dev"
region = "eu-central-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=dev"

[prod.deploy.parameters]
stack_name = "s3-sns-prod"
s3_bucket = "s3-sns-sam-artifacts"
s3_prefix = "prod"
region = "eu-central-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=prod"